<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Invoice Financial Report</title>
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 11px; color: #333333; line-height: 1.4; margin: 0; padding: 15px; }
        .header-table { width: 100%; margin-bottom: 20px; border-bottom: 2px solid #2563eb; padding-bottom: 12px; }
        .company-name { font-size: 18px; font-weight: bold; color: #2563eb; }
        .report-title { font-size: 20px; font-weight: bold; color: #111827; text-align: right; }
        .summary-box { background: #f8fafc; padding: 10px; border-radius: 6px; border: 1px solid #e2e8f0; margin-bottom: 20px; }
        .data-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        .data-table th { background: #0f172a; color: #ffffff; padding: 7px 9px; font-size: 10px; text-transform: uppercase; text-align: left; }
        .data-table td { padding: 7px 9px; border-bottom: 1px solid #e2e8f0; font-size: 10px; }
        .text-end { text-align: right; }
        .fw-bold { font-weight: bold; }
        .text-success { color: #16a34a; }
        .text-danger { color: #dc2626; }
        .text-primary { color: #2563eb; }
        .footer { margin-top: 30px; border-top: 1px solid #e2e8f0; padding-top: 10px; text-align: center; font-size: 9px; color: #64748b; }
    </style>
</head>
<body>

<table class="header-table">
    <tr>
        <td style="width: 50%; vertical-align: top;">
            <div class="company-name">{{ $company->company_name }}</div>
            <div style="font-size: 10px; color: #64748b;">
                {{ $company->address }}, {{ $company->city }}, {{ $company->country }}<br>
                Email: {{ $company->email }}
            </div>
        </td>
        <td style="width: 50%; text-align: right; vertical-align: top;">
            <div class="report-title">INVOICE FINANCIAL REPORT</div>
            <div style="font-size: 10px; color: #64748b; margin-top: 4px;">
                <strong>Financial Period:</strong> {{ $fyTitle }}<br>
                <strong>Date Generated:</strong> {{ date('M d, Y') }}
            </div>
        </td>
    </tr>
</table>

<div class="summary-box">
    <table style="width: 100%;">
        <tr>
            <td style="width: 25%;">Total Invoices: <strong>{{ $summary['count'] }}</strong></td>
            <td style="width: 25%;">Total Billed: <strong class="text-primary">${{ number_format($summary['total'], 2) }}</strong></td>
            <td style="width: 25%;">Total Collected: <strong class="text-success">${{ number_format($summary['paid'], 2) }}</strong></td>
            <td style="width: 25%;">Total Outstanding: <strong class="text-danger">${{ number_format($summary['balance'], 2) }}</strong></td>
        </tr>
    </table>
</div>

<table class="data-table">
    <thead>
        <tr>
            <th>Invoice #</th>
            <th>Client</th>
            <th>Invoice Date</th>
            <th>Due Date</th>
            <th class="text-end">Total</th>
            <th class="text-end">Paid</th>
            <th class="text-end">Balance</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        @forelse($invoices as $inv)
        <tr>
            <td class="fw-bold">{{ $inv->invoice_number }}</td>
            <td>{{ $inv->client->company_name }}</td>
            <td>{{ $inv->invoice_date->format('Y-m-d') }}</td>
            <td>{{ $inv->due_date->format('Y-m-d') }}</td>
            <td class="text-end fw-bold">${{ number_format($inv->grand_total, 2) }}</td>
            <td class="text-end text-success">${{ number_format($inv->paid_amount, 2) }}</td>
            <td class="text-end text-danger fw-bold">${{ number_format($inv->balance_due, 2) }}</td>
            <td>{{ $inv->status }}</td>
        </tr>
        @empty
        <tr>
            <td colspan="8" style="text-align: center; color: #64748b; padding: 15px;">No records found for this period.</td>
        </tr>
        @endforelse
    </tbody>
</table>

<div class="footer">
    Generated by Assertiv Logix Invoice Management System &bull; {{ date('Y-m-d H:i:s') }}
</div>

</body>
</html>
