<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Payment Transactions Report</title>
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 11px; color: #333333; line-height: 1.4; margin: 0; padding: 15px; }
        .header-table { width: 100%; margin-bottom: 20px; border-bottom: 2px solid #16a34a; padding-bottom: 12px; }
        .company-name { font-size: 18px; font-weight: bold; color: #16a34a; }
        .report-title { font-size: 20px; font-weight: bold; color: #111827; text-align: right; }
        .summary-box { background: #f8fafc; padding: 10px; border-radius: 6px; border: 1px solid #e2e8f0; margin-bottom: 20px; }
        .data-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        .data-table th { background: #0f172a; color: #ffffff; padding: 7px 9px; font-size: 10px; text-transform: uppercase; text-align: left; }
        .data-table td { padding: 7px 9px; border-bottom: 1px solid #e2e8f0; font-size: 10px; }
        .text-end { text-align: right; }
        .fw-bold { font-weight: bold; }
        .text-success { color: #16a34a; }
        .footer { margin-top: 30px; border-top: 1px solid #e2e8f0; padding-top: 10px; text-align: center; font-size: 9px; color: #64748b; }
    </style>
</head>
<body>

<table class="header-table">
    <tr>
        <td style="width: 50%; vertical-align: top;">
            <div class="company-name">{{ $company->company_name }}</div>
            <div style="font-size: 10px; color: #64748b;">
                {{ $company->address }}, {{ $company->city }}, {{ $company->country }}<br>
                Email: {{ $company->email }}
            </div>
        </td>
        <td style="width: 50%; text-align: right; vertical-align: top;">
            <div class="report-title">PAYMENT TRANSACTIONS REPORT</div>
            <div style="font-size: 10px; color: #64748b; margin-top: 4px;">
                <strong>Financial Period:</strong> {{ $fyTitle }}<br>
                <strong>Date Generated:</strong> {{ date('M d, Y') }}
            </div>
        </td>
    </tr>
</table>

<div class="summary-box">
    <table style="width: 100%;">
        <tr>
            <td style="width: 50%;">Total Transactions: <strong>{{ count($payments) }}</strong></td>
            <td style="width: 50%; text-align: right;">Total Amount Received: <strong class="text-success" style="font-size: 13px;">${{ number_format($totalAmount, 2) }}</strong></td>
        </tr>
    </table>
</div>

<table class="data-table">
    <thead>
        <tr>
            <th>Payment ID</th>
            <th>Client</th>
            <th>Invoice #</th>
            <th>Payment Date</th>
            <th>Method</th>
            <th>Transaction ID</th>
            <th class="text-end">Amount</th>
        </tr>
    </thead>
    <tbody>
        @forelse($payments as $p)
        <tr>
            <td class="fw-bold" style="color: #2563eb;">{{ $p->payment_id }}</td>
            <td>{{ $p->client->company_name }}</td>
            <td>{{ $p->invoice ? $p->invoice->invoice_number : 'N/A' }}</td>
            <td>{{ $p->payment_date->format('Y-m-d') }}</td>
            <td>{{ $p->payment_method }}</td>
            <td>{{ $p->transaction_id ?: 'N/A' }}</td>
            <td class="text-end text-success fw-bold">+${{ number_format($p->amount, 2) }}</td>
        </tr>
        @empty
        <tr>
            <td colspan="7" style="text-align: center; color: #64748b; padding: 15px;">No payment records found for this period.</td>
        </tr>
        @endforelse
    </tbody>
</table>

<div class="footer">
    Generated by Assertiv Logix Invoice Management System &bull; {{ date('Y-m-d H:i:s') }}
</div>

</body>
</html>
