<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Client Revenue Breakdown Report</title>
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 11px; color: #333333; line-height: 1.4; margin: 0; padding: 15px; }
        .header-table { width: 100%; margin-bottom: 20px; border-bottom: 2px solid #eab308; padding-bottom: 12px; }
        .company-name { font-size: 18px; font-weight: bold; color: #ca8a04; }
        .report-title { font-size: 20px; font-weight: bold; color: #111827; text-align: right; }
        .data-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        .data-table th { background: #0f172a; color: #ffffff; padding: 8px 10px; font-size: 10px; text-transform: uppercase; text-align: left; }
        .data-table td { padding: 8px 10px; border-bottom: 1px solid #e2e8f0; font-size: 10px; }
        .text-end { text-align: right; }
        .fw-bold { font-weight: bold; }
        .text-success { color: #16a34a; }
        .text-danger { color: #dc2626; }
        .footer { margin-top: 30px; border-top: 1px solid #e2e8f0; padding-top: 10px; text-align: center; font-size: 9px; color: #64748b; }
    </style>
</head>
<body>

<table class="header-table">
    <tr>
        <td style="width: 50%; vertical-align: top;">
            <div class="company-name">{{ $company->company_name }}</div>
            <div style="font-size: 10px; color: #64748b;">
                {{ $company->address }}, {{ $company->city }}, {{ $company->country }}<br>
                Email: {{ $company->email }}
            </div>
        </td>
        <td style="width: 50%; text-align: right; vertical-align: top;">
            <div class="report-title">CLIENT REVENUE BREAKDOWN</div>
            <div style="font-size: 10px; color: #64748b; margin-top: 4px;">
                <strong>Financial Period:</strong> {{ $fyTitle }}<br>
                <strong>Date Generated:</strong> {{ date('M d, Y') }}
            </div>
        </td>
    </tr>
</table>

<table class="data-table">
    <thead>
        <tr>
            <th>Client ID</th>
            <th>Company Name</th>
            <th>Total Invoices</th>
            <th class="text-end">Total Revenue</th>
            <th class="text-end">Paid Amount</th>
            <th class="text-end">Outstanding Balance</th>
        </tr>
    </thead>
    <tbody>
        @foreach($clients as $c)
        <tr>
            <td class="fw-bold" style="color: #2563eb;">{{ $c['client_id'] }}</td>
            <td class="fw-bold">{{ $c['company_name'] }}</td>
            <td>{{ $c['total_invoices'] }}</td>
            <td class="text-end fw-bold">${{ number_format($c['total_revenue'], 2) }}</td>
            <td class="text-end text-success fw-bold">${{ number_format($c['paid'], 2) }}</td>
            <td class="text-end text-danger fw-bold">${{ number_format($c['outstanding'], 2) }}</td>
        </tr>
        @endforeach
    </tbody>
</table>

<div class="footer">
    Generated by Assertiv Logix Invoice Management System &bull; {{ date('Y-m-d H:i:s') }}
</div>

</body>
</html>
