<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tax Collection Summary Report</title>
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 11px; color: #333333; line-height: 1.4; margin: 0; padding: 15px; }
        .header-table { width: 100%; margin-bottom: 20px; border-bottom: 2px solid #06b6d4; padding-bottom: 12px; }
        .company-name { font-size: 18px; font-weight: bold; color: #0891b2; }
        .report-title { font-size: 20px; font-weight: bold; color: #111827; text-align: right; }
        .summary-box { background: #f8fafc; padding: 10px; border-radius: 6px; border: 1px solid #e2e8f0; margin-bottom: 20px; }
        .data-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        .data-table th { background: #0f172a; color: #ffffff; padding: 8px 10px; font-size: 10px; text-transform: uppercase; text-align: left; }
        .data-table td { padding: 8px 10px; border-bottom: 1px solid #e2e8f0; font-size: 10px; }
        .text-end { text-align: right; }
        .fw-bold { font-weight: bold; }
        .text-primary { color: #0891b2; }
        .footer { margin-top: 30px; border-top: 1px solid #e2e8f0; padding-top: 10px; text-align: center; font-size: 9px; color: #64748b; }
    </style>
</head>
<body>

<table class="header-table">
    <tr>
        <td style="width: 50%; vertical-align: top;">
            <div class="company-name">{{ $company->company_name }}</div>
            <div style="font-size: 10px; color: #64748b;">
                {{ $company->address }}, {{ $company->city }}, {{ $company->country }}<br>
                Email: {{ $company->email }}
            </div>
        </td>
        <td style="width: 50%; text-align: right; vertical-align: top;">
            <div class="report-title">TAX COLLECTION SUMMARY</div>
            <div style="font-size: 10px; color: #64748b; margin-top: 4px;">
                <strong>Financial Period:</strong> {{ $fyTitle }}<br>
                <strong>Date Generated:</strong> {{ date('M d, Y') }}
            </div>
        </td>
    </tr>
</table>

<div class="summary-box">
    <div style="font-weight: bold; font-size: 11px; margin-bottom: 6px;">Tax Summary Breakdown:</div>
    <table style="width: 100%;">
        <tr>
            @foreach($taxSummary as $ts)
            <td style="padding-right: 15px;">
                {{ $ts->tax_name }} ({{ $ts->tax_rate }}%): <strong class="text-primary">${{ number_format($ts->total_tax, 2) }}</strong>
            </td>
            @endforeach
        </tr>
    </table>
</div>

<table class="data-table">
    <thead>
        <tr>
            <th>Tax Name</th>
            <th>Tax Rate</th>
            <th class="text-end">Tax Amount</th>
            <th>Invoice Number</th>
            <th>Client</th>
        </tr>
    </thead>
    <tbody>
        @forelse($taxRecords as $tr)
        <tr>
            <td class="fw-bold">{{ $tr->tax_name }}</td>
            <td>{{ $tr->tax_rate }}%</td>
            <td class="text-end text-primary fw-bold">${{ number_format($tr->tax_amount, 2) }}</td>
            <td>{{ $tr->invoice ? $tr->invoice->invoice_number : 'N/A' }}</td>
            <td>{{ $tr->invoice && $tr->invoice->client ? $tr->invoice->client->company_name : 'N/A' }}</td>
        </tr>
        @empty
        <tr>
            <td colspan="5" style="text-align: center; color: #64748b; padding: 15px;">No tax records found for this period.</td>
        </tr>
        @endforelse
    </tbody>
</table>

<div class="footer">
    Generated by Assertiv Logix Invoice Management System &bull; {{ date('Y-m-d H:i:s') }}
</div>

</body>
</html>
